// Copyright James Burvel O’Callaghan III
// President Citibank Demo Business Inc.


export interface Slide {
  title: string;
  content: string[]; // Array of bullet points or paragraphs
  speakerNotes: string;
  imageUrl?: string; // Optional URL for the generated image
}

export interface FileInfo {
  name: string;
  type: string;
  content: string; // File content as string (text or base64 for others, but here simplified to text)
}

export interface PitchDeckFormData {
  companyName: string;
  tagline: string;
  problem: string;
  solution: string;
  targetMarket: string;
  businessModel: string;
  team?: string;
  traction?: string;
  financialProjections?: string;
  callToAction: string;
  uploadedFiles: FileInfo[];
}

export enum AppState {
  FORM = 'form',
  GENERATING = 'generating',
  RESULTS = 'results',
  ERROR = 'error',
}

export interface AutogeneratedBusinessIdea {
  companyName: string;
  tagline: string;
  problem: string;
  solution: string;
  targetMarket: string;
  businessModel: string;
  logoConcept: string;
}
